# Generated by Django 2.2.8 on 2023-12-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerName', models.CharField(max_length=255)),
                ('DateOfJourney', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('FlightNumber', models.IntegerField()),
                ('PNRNumber', models.IntegerField()),
                ('BaggageSpace', models.IntegerField()),
            ],
        ),
    ]
