# Generated by Django 3.2.15 on 2023-12-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_postmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='id',
            new_name='idP',
        ),
    ]
