# Generated by Django 3.2.15 on 2023-12-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_id_postmodel_idp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='idP',
            new_name='id',
        ),
    ]
