# Generated by Django 3.2.15 on 2023-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_idp_postmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='BaggageSpace',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='DateOfJourney',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='FlightNumber',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='PNRNumber',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='PassengerName',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
