# Generated by Django 3.2.15 on 2023-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20231214_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='baggage_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='destination',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='flight_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='passenger_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='pnr_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='source',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
