# Generated by Django 3.2.15 on 2023-12-14 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20231214_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='date_of_journey',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
