# Generated by Django 3.2.15 on 2023-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_postmodel_date_of_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='baggage_space',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date_of_journey',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='flight_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='passenger_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pnr_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
